env: "development"
database_url: "host=pg_db port=5432 user=postgres password=root dbname=notes sslmode=disable"
token_ttl: 1h
session_key: "f32tfaytg3#Y4h,.l^I46mkq@#!$vyVQ#Y142tv49*4v/*t/v5456avf.,m@!cag"
http_server:
 address: ":4050"
 timeout: 4s
 idle_timeout: 60s